### ISSUE TITLE
probleme with some input file 

### ISSUE THREAD

**Issue by aurelBZH** [qinzhu/PIVOT#2]
hi Quin, 
thanks for your great app.
I have a directory with some count file, one by sample ( i join you one of the file [319B.feature.count.txt](https://github.com/qinzhu/PIVOT/files/1639867/test.feature.count.txt)) . It's tsv file with gene and count. When i try to upload them on  Pivot i have an error message like this 
![pivot_error_message](https://user-images.githubusercontent.com/9987970/35055564-c8db7b32-fbaf-11e7-9754-ef475f1c367e.png)
 . I think i have missed something but can't figure what.

ps we might be interested in a server version of your app. 

Thanks for your help

Aurélien Béliard

**Comment by qinzhu** [comment]
Hello Aurélien,

Thanks for finding this bug. I found it happens when you use DESeq normalization and your input is not integer (Note that your data has decimal points, DESeq require int input). I've added a fix which automatically rounds up the non-int values if you use DESeq. Please update PIVOT with install_github("qinzhu/PIVOT") and see if it works with your data.

I'll release server version of PIVOT as soon as I can. Thanks again for the bug report and your interest in using PIVOT.

Best,
Qin

**Comment by aurelBZH** [comment]
thanks for your quick response, it work now.
